# Generated by Django 4.0 on 2021-12-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpling',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
