# Generated by Django 4.0 on 2021-12-31 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_dumpling_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fold', models.CharField(choices=[('M', 'Morning'), ('N', 'Noon'), ('E', 'Evening')], default='M', max_length=1)),
                ('dumpling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dumpling')),
            ],
        ),
    ]
